"""add updated_at to reorder_decisions

Revision ID: daa489c1d5ee
Revises: 8597118bd649
Create Date: 2026-06-21 04:19:21.508726

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'daa489c1d5ee'
down_revision: Union[str, Sequence[str], None] = '8597118bd649'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reorder_decisions', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reorder_decisions', 'updated_at')
    # ### end Alembic commands ###
